FROM centos:7
LABEL maintainer="github@jakoberpf.de"

COPY ../zerotier-installer.sh /installer.sh
COPY ../zerotier-join.sh /join.sh
COPY ../zerotier-leave.sh /leave.sh

ENTRYPOINT ["sleep", "infinity"]
