FROM centos:8

COPY zerotier-installer.sh /zerotier-installer.sh
RUN /zerotier-installer.sh

COPY zerotier-start.sh /zerotier-start.sh
COPY zerotier-join.sh /zerotier-join.sh
COPY zerotier-leave.sh /zerotier-leave.sh

ENTRYPOINT ["entrypoint.sh"]
