name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build images
        working-directory: ./test
        run: |
          docker compose -f docker-compose.yaml build

      - name: Run tests
        working-directory: ./test
        run: |
          ./helpers/bats/bin/bats install.bats

  docker:
    name: Build and push image

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: jakoberpf/zerotier-scripts

      - name: Build image and push to Docker Hub tagged with the branchname
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jakoberpf/zerotier-scripts:latest
          labels: ${{ steps.meta.outputs.labels }}
