name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build images
        working-directory: ./test
        run: |
          docker compose -f docker-compose.yaml build

      - name: Run tests
        working-directory: ./test
        run: |
          ./helpers/bats/bin/bats install.bats

  docker:
    name: Build and push image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-scripts
        uses: docker/metadata-action@v5
        with:
          images: jakoberpf/zerotier-scripts

      - name: Build image and push to Docker Hub tagged with scripts
        uses: docker/build-push-action@v4
        with:
          context: .
          file: test/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jakoberpf/zerotier-scripts:scripts
          labels: ${{ steps.meta-scripts.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-client
        uses: docker/metadata-action@v5
        with:
          images: jakoberpf/zerotier-client

      - run: echo "VERSION_TAG=$(cat Dockerfile | grep VERSION -m 1 | tr "=" " " | cut -d " " -f3)" >> $GITHUB_ENV

      - name: Build image and push to Docker Hub tagged with latest
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            jakoberpf/zerotier-client:latest
            jakoberpf/zerotier-client:${{ env.VERSION_TAG }}
          labels: ${{ steps.meta-client.outputs.labels }}
