name: release

on: 
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          submodules: recursive
      - name: Build Images
        working-directory: ./test
        run: |
          docker compose -f docker-compose.yaml build
      - name: Run Tests
        working-directory: ./test
        run: |
          ./helpers/bats/bin/bats install.bats

  release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          submodules: recursive
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            zerotier-installer.sh
            zerotier-join.sh
            zerotier-leave.sh
            README.md
          body: ${{ steps.github_release.outputs.changelog }}
