name: release

on: 
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          zerotier-installer.sh
          zerotier-join.sh
          zerotier-leave.sh
          README.md
        body: ${{ steps.github_release.outputs.changelog }}
