name: test

on: 
  - push
  - pull_request

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Images
        working-directory: ./test
        run: |
          docker compose -f docker-compose.yaml build
      - name: Run Images
        working-directory: ./test
        run: |
          ./bats/bin/bats test.bats
