name: test

on: 
  - push
  - pull_request

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build Images
        working-directory: ./test
        run: |
          docker compose -f docker-compose.yaml build
      - name: Run Tests
        working-directory: ./test
        run: |
          ./helpers/bats/bin/bats install.bats
